name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -mod vendor -v .

    - name: Test building go-mail-preview
      working-directory: ./go-mail-preview
      run: go build .

    - name: Test Mailgun
      env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        EXAMPLE_MAIL_ADDRESS: ${{ secrets.EXAMPLE_MAIL_ADDRESS }}
      working-directory: ./provider/mailgun      
      run: go test -mod vendor -v .
